### ISSUE TITLE
How to compile go application

### ISSUE THREAD

**Issue by kbarter** [tobias-kuendig/hacompanion#1]
Thanks for making this.  When I was installing this, I noticed that there are a couple of steps that would be useful:

- add short instruction on cloning the repository
- `git clone https://github.com/tobias-kuendig/hacompanion.git`
- add command for compiling the application
- `cd hacompanion`
- `go build`

I think this would help those people who are not familiar with those tasks, and make you instructions complete.

Other than that, this was easy to install, and get running.

**Comment by tobias-kuendig** [comment]
You can download the compiled binary here:

https://github.com/tobias-kuendig/hacompanion/releases (`_binary` are the compiled Go binaries)

**Comment by tobias-kuendig** [comment]
I have added a few lines regarding the installation to the README, thanks @kbarter!

https://github.com/tobias-kuendig/hacompanion/commit/7f92a694d17610465f70c5d83204d186e2ee8750
