### ISSUE TITLE
Updating github releases

### ISSUE THREAD

**Issue by Ramblurr** [tobias-kuendig/hacompanion#41]
Hi there @tobias-kuendig 

Do you have any plans to update the https://github.com/tobias-kuendig/hacompanion/releases in the future?

I notice it hasn't been updated since 1.0.7, but the latest tag is 1.0.11.

No worries if you don't plan too.. but maybe you just forgot?

Github releases are nice because they can function as a Changelog which is useful for linux distro packagers like myself.

**Comment by tobias-kuendig** [comment]
Thank you for the feedback, @Ramblurr! The build pipeline has been broken for some time now, that's why no new releases were pushed to GitHub. I have fixed this issue, so future releases will be generated corretly again.
