### ISSUE TITLE
Unable to install on Fedora

### ISSUE THREAD

**Issue by G-D-D-971** [tobias-kuendig/hacompanion#44]
Installation on Fedora is impossible because according to my tests the package recognition install does not work as planned...
So I have:
```
Error:
Problem: conflicting requests
- nothing provides lm-sensors needed by hacompanion-1.0.12-1.x86_64 from @commandline
- nothing provides iputils-ping needed by hacompanion-1.0.12-1.x86_64 from @commandline
- nothing provides libnotify-bin needed by hacompanion-1.0.12-1.x86_64 from @commandline
(Try adding "--skip-broken" to ignore non-installable packages)
```
So I'm trying to check if these packages are installed:
```
Sudo yum install lm-sensors iputils-ping libnotify-bin
Last check of the expiration of metadata carried out 0:26:27 ago on Thu. 09 May 2024 15:57:16.
No correspondence for the parameter: lm-sensors
No match for the parameter: iputils-ping
No match for the parameter: libnotify-bin
Error: Unable to find a match: lm-sensors iputils-ping libnotify-bin
```
After some research I'm capable to install all packages
```
Sudo yum install lm_sensors iputils libnotify
Last check of the expiration of the metadata carried out 0:28:25 on Thu. 09 May 2024 15:57:16.
The lm_sensors-3.6.0-14.fc39.x86_64 package is already installed.
The iputils-20221126-4.fc39.x86_64 package is already installed.
The libnotify-0.8.3-1.fc39.x86_64 package is already installed.
Dependencies resolved.
Nothing to do.
Done!
```
But the installation din't detect the package.

**Comment by Rittsel** [comment]
Same here - here's a workaround though to just install it manually from the rpm package - it'll unpack the binary to **/usr/bin/** as if you would install it with yum or dnf.

`rpm2cpio hacompanion_1.0.15_linux_amd64.rpm | sudo cpio -idmv`

**Comment by G-D-D-971** [comment]
Thanks a lot for your solution @Rittsel, It work perfectly. 
For people try to start the hacompanion with systemd on load I have one conseil to you, set the absolute path of the files, disable `EnvironmentFile` with an `#`
I hope this can help you ;)

**Comment by G-D-D-971** [comment]
> So I don't get why the issue is closed when it's not resolved.
Hello @CaptainMalu, the issue is closed because I abandoned, I had succeeded by a miracle that I no longer remember running and operating hacompanion but due to a bug or a problem the package made the system unstable, ended up making it impossible to boot or work properly (cockpit and other system services no longer working properly) because the package arrived by a way that I did not find to fill a partition link to the boot that is not possible to empty once filled (unfortunately I no longer remember the partition in question but it was linked to the hardware).

So I decided to stop trying and close the problem since the original problem had been solved (the impossibility of using and installing hacompanion).
P.S: @Rittsel had provided a solution and the last message I left gives a functional solution.
In addition, it is necessary (as specified in the first message) to install similar packages.
I don't know if the problem with the partition still exists and I haven't tried to use the package again since I detected the problem.
You must also use the `.db` if my memories are correct...
Remember that I had this problem with Fedora Server, if you used another distribution or another RedHat operating system, I will not be able to help you, so my experience is a bit far but I would see if there are any remains of the package as well as configuration.

**Comment by G-D-D-971** [comment]
> This is probably due to the dependencies not having the same name on every distro:

Yes the advantage anyway is that the code is open-source so if you want to make a specific fork for Fedora it could interest a lot of person (including the creator himself...)
